import type { components } from './generated';

export type ApiSchemas = components['schemas'];
export type TaskStage = ApiSchemas['TaskStage'];
export type TaskEventType = ApiSchemas['TaskEventType'];
export type TaskEventPayload = ApiSchemas['TaskEventPayload'];
export type TaskEvent = ApiSchemas['TaskEvent'];
export type StatusResponse = ApiSchemas['StatusResponse'];
export type ResultSuccess = ApiSchemas['ResultSuccess'];
export type CreateTaskResponse = ApiSchemas['CreateTaskResponse'];
export type AuthFeaturesResponse = ApiSchemas['AuthFeaturesResponse'];
export type AuthLoginResponse = ApiSchemas['AuthLoginResponse'];
export type TaskListItemResponse = ApiSchemas['TaskListItemResponse'];
export type TaskHistoryRecord = ApiSchemas['TaskHistoryRecord'];
export type TaskDeletedResponse = ApiSchemas['TaskDeletedResponse'];
export type TaskUndeletedResponse = ApiSchemas['TaskUndeletedResponse'];
export type ErrorResponse = ApiSchemas['ErrorResponse'];
export type UserBucketListItem = ApiSchemas['UserBucketListItem'];
export type UserBucketListResponse = ApiSchemas['UserBucketListResponse'];
export type UserBucketResponse = ApiSchemas['UserBucketResponse'];
export type ServiceTokenItem = ApiSchemas['ServiceTokenItem'];
export type ServiceTokenListResponse = ApiSchemas['ServiceTokenListResponse'];
export type ServiceTokenCreatedResponse = ApiSchemas['ServiceTokenCreatedResponse'];
export type RevokedResponse = ApiSchemas['RevokedResponse'];
export type UploadCleanupCandidate = ApiSchemas['UploadCleanupCandidate'];
export type UploadCleanupListResponse = ApiSchemas['UploadCleanupListResponse'];
export type UploadCleanupDeleteResponse = ApiSchemas['UploadCleanupDeleteResponse'];
export type AuthLogoutResponse = ApiSchemas['AuthLogoutResponse'];
